### ISSUE TITLE
afterCloseInfowindow don't fire after close

### ISSUE THREAD

**Issue by rogerburkhard** [danielemoraschi/maplace.js#137]
It seems that the events "afterCloseInfowindow" and "beforeCloseInfowindow" don't fire after closing the InfoWindow. Both events fire only when I close the InfoWindow and on reopen the fire. But I need the event to be fired when I close the InfoWindow. Any help is very appreciated.

**Comment by douglas-andrew-harley** [comment]
Please not that both beforeCloseInfowindow and afterCloseInfowindow This issue is rather troublesome, as I cannot find a way to work around it...I am attempting to use afterCloseInfowindow events to reset the map to its original state after closing a marker info window (i.e., to functionally zoom out and re-center).

I have provided a screen recording showing the exact problems here: https://www.youtube.com/watch?v=XpuNFug6gaE
