### ISSUE TITLE
Route with a user defined starter point

### ISSUE THREAD

**Issue by adaniello** [danielemoraschi/maplace.js#169]
I have a map with multiple points.
I'ld like to get directions by an user defined starter point (eg. user location) to a point in the list (eg. a point selected by user).
Any suggestion to do this task?
Why not add to maplace also a "my location button" as in google maps?
Thanks

**Comment by danielemoraschi** [comment]
Directions are always created by user defined points:
```
new Maplace({
    locations:[{
        lat: 45.4654,
        lon: 9.1866,
        title: 'Milan, Italy',
    },{
        lat: 48.892,
        lon: 2.359,
        title: 'Paris, France',
    }],
    generate_controls: false,
    show_markers: false,
    type: 'directions'
}).Load();
``` 
How to populate the locations parameter is responsibility of your application, and not MaplaceJs. Same is valid for the user location, which should come from your implementation (or business logic) and not by the helper.
To give you an idea, for your "my location button" I would do something similar to this: https://jsfiddle.net/_tomorro/q9htfqmL/

**Comment by adaniello** [comment]
@danielemoraschi many thanks, but i have this scenario:
- i have locations parameter that define ca 25 points;
- user should be able to select one of these points and get directions from his location to this point;
- locations parameter should be retain initial list of points.

Any suggestion for this?

Thanks in advance

**Comment by danielemoraschi** [comment]
The only problem with this is that you are trying to display two different views or "layers" on the map: one with all the markers, the second one the direction from the current location to one of those points. Since Maplace doesn't support multiple layers you can only achieve that via creating the menu as a fixed list in your html page, and generate the directions view when clicking on one of the items, and use the "view all" menu item to switch back the view to all the markers.

**Comment by adaniello** [comment]
I'll try as your suggestion.
Thanks
