### ISSUE TITLE
Filterable List

### ISSUE THREAD

**Issue by terrybarth** [danielemoraschi/maplace.js#40]
I've used maplace on a couple of projects and thinks just great! Thanks for making it available.

I'm wondering if it is possible to maek menu list filterable by group such as restaurants, schools, etc.?

It would be a combination of menu demo you have on your site and something like this http://www.geocodezip.com/v2_MarkerCheckBoxes.asp

Thanks!

**Comment by Marc-pi** [comment]
@danielemoraschi hello, is this already available in latest code, we are looking for this too ?

**Comment by danielemoraschi** [comment]
To support that you just have to develop a new menu type, something very similar to what I did in the "Menu Docs" page on the main website.
That's only a simple a demo, but I suggest you to try play with it, because effectively you can add already your own menu types.
Since I want to keep the library the small as possible, any new menu type ideally should be released as a separate module. For sure a thing for one of the future releases.

Thanks

**Comment by Marc-pi** [comment]
you mean this doc is related to this ?
![menu](https://cloud.githubusercontent.com/assets/919332/13427490/b3e087c2-dfb4-11e5-8852-e221e4a681ce.PNG)

or it is a new menu displayed on the map with checkboxes?

**Comment by danielemoraschi** [comment]
No, I mean this doc:

![screen shot 2016-03-01 at 13 09 49](https://cloud.githubusercontent.com/assets/872066/13427919/f84f90d4-dfae-11e5-99ce-ed0d2670bb68.png)
